language: java
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - shubhamr837@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
before_install:
- curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
- unzip awscli-bundle.zip
- sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
- export AWS_ACCESS_KEY_ID=AKIASTFVKUSNQXINESXB
- export AWS_SECRET_ACCESS_KEY=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
- export AWS_DEFAULT_REGION=us-east-2
script:
- ./mvnw package
- $(aws ecr get-login --no-include-email --region us-east-2)
- docker build -t shubhamr837 .
- docker tag shubhamr837:latest 178621424795.dkr.ecr.us-east-2.amazonaws.com/shubhamr837:zuul-proxy
- docker push 178621424795.dkr.ecr.us-east-2.amazonaws.com/shubhamr837:zuul-proxy
