steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=firebase_secrets.json.enc
      - --plaintext-file=firebase_secrets.json
      - --location=global
      - --keyring=pdf_keyring
      - --key=pdf-key
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['package','-Dmaven.test.skip=true']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/crested-ratio-257703/zuul-proxy', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/crested-ratio-257703/zuul-proxy']