server:
  port: 80
ribbon:
  ReadTimeout: 90000
  connection-timeout: 50000
  eureka:
    enabled: true
zuul:
  ignored-services: '*'
  routes:
    pdftoword: /pdftoword/**
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://EurekaService:80/eureka/