server:
  port: 80
ribbon:
  ReadTimeout: 60000
  connection-timeout: 30000
  eureka:
    enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://10.0.1.80/eureka/