apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zuul
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zuul
    spec:
      containers:
        - name: zuul
          image: gcr.io/crested-ratio-257703/zuul-proxy:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
