apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zuul
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zuul
    spec:
      containers:
        - name: zuul
          image: 178621424795.dkr.ecr.us-east-2.amazonaws.com/shubhamr837:zuul-proxy
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80